version: "3.8"

services: 
  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - biblio-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: $${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: $${{secrets.MYSQL_DATABASE}}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: yelp-ea-api
    build:
      context: ./yelp-ea-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: $${{secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: $${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: $${{secrets.SPRING_DATASOURCE_PASSWORD}}	
    depends_on:
      mysqldb:
        condition: service_healthy

  db-seed:
    image: mysql:8.0
    volumes:
      - ./data/mock_data.sql:/mock_data.sql
    entrypoint: >
      bash -c "
        echo '🕒 Attente que la DB soit prête...';
        sleep 10;
        echo '⏳ Attente du backend (création des tables)...';
        sleep 20;
        echo '🚀 Insertion des données';
        mysql -h mysqldb -uapp_user -papp_password yelp < /mock_data.sql;
        echo '✅ Données injectées';
      "
    depends_on:
      backend:
        condition: service_started

  frontend:
    image: yelp-ea-front
    build:
      context: ./yelp-ea
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  biblio-mysql-data:
