version: "3.8"

services: 
  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - biblio-mysql-data:/var/lib/mysql
    environment: 
       MYSQL_ROOT_PASSWORD: $${{secrets.MYSQL_ROOT_PASSWORD}}
       MYSQL_DATABASE: $${{secrets.MYSQL_DATABASE}}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: yelp-ea-api
    build:
      context: ./yelp-ea-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: $${{secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: $${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: $${{secrets.SPRING_DATASOURCE_PASSWORD}}
    depends_on:
      mysqldb:
        condition: service_healthy


  frontend:
    image: yelp-ea-front
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  biblio-mysql-data: