name: CiCd

on:
  push:
    branches: [ "back" ]
  pull_request:
    branches: [ "back" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installer Docker avec une action dédiée
      - name: Docker install avec action
        uses: docker-practice/actions-setup-docker@master

      # Vérifier la version de Docker
      - name: Check Docker version
        run: docker --version

      # Vérifier le statut de Docker
      - name: Check Docker status
        run: sudo systemctl status docker

      # Créer un fichier de configuration daemon.json si nécessaire
      - name: Create daemon.json
        run: |
          if [ ! -f /etc/docker/daemon.json ]; then
            echo '{"storage-driver": "overlay2"}' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
          fi

      # Installer Docker Compose via CLI
      - name: Compose in CLI
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

      # Test Unitaire
      - name: Run unit tests
        run: mvn test

      # Teardown : arrêter les services Docker
      - name: Teardown (docker-compose down)
        run: docker-compose down

      # Se connecter à Docker
      - name: Docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Docker build
        run: docker build -t my-app .

      # Pousser l'image Docker vers le registre
      - name: Docker push
        run: docker push my-app
