name: CiCd

on:
  push:
    branches: [ "back" ]
  pull_request:
    branches: [ "back" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Étape de Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Installer Docker avec une action dédiée
      - name: Docker install avec action
        run: |
          # Mettre à jour le package apt
          sudo apt-get update
          
          # Installer les dépendances nécessaires
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          # Ajouter la clé GPG officielle de Docker
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          # Ajouter le dépôt Docker
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          # Mettre à jour les sources de package après ajout du dépôt Docker
          sudo apt-get update
          # Installer Docker
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          # Vérifier que Docker est bien installé
          sudo docker --version
      # Installer Docker Compose via CLI
      - name: Compose in CLI
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          # Ajouter docker-compose au PATH
          sudo ln -s $DOCKER_CONFIG/cli-plugins/docker-compose /usr/local/bin/docker-compose
      # Vérifier l'installation de Docker Compose
      #- name: Verify Docker Compose installation
      #  run: |
      #    docker-compose --version

      # Installer Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Test Unitaire back
      - name: Run unit tests
        run: |
          cd yelp-ea-api
          mvn package

      - name: Install dependencies for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -y install -f

      - name: Install Python dependencies for Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      
      - name: Vérifier la présence du script Selenium
        run: ls -l selenium
      
      - name: Installer les dépendances Selenium
        run: pip install selenium webdriver-manager

      - name: Run Selenium tests
        run: |
          cd selenium
          python selenium_test_script.py 

      # Teardown : arrêter les services Docker
      - name: Teardown (docker-compose down)
        run: docker-compose down
        
      # Se connecter à Docker
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      #    password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          
      # Construire l'image Docker
      #- name: Docker build
      #  run: |
      #    cd yelp-ea-api
      #    docker build -t my-app .

      # Pousser l'image Docker vers le registre
      #- name: Docker push
      #  run: docker push my-app
