on:
  push:
    branches: [ "main", "back" ]
  pull_request:
    branches: [ "main", "back" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo docker --version
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

  build_backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cd yelp-ea-api
          mvn clean package -DskipTests
      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: yelp-ea-api/target/*.jar

  unit_tests:
    needs: build_backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          cd yelp-ea-api
          mvn test

  angular_server:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start Angular server
        run: |
          cd yelp-ea
          npm install
          npm run start -- --host 0.0.0.0 --disable-host-check &
      - name: Wait for Angular server to start
        run: |
          until curl -s http://localhost:4200 > /dev/null; do
            echo "Waiting for Angular to start..."
            sleep 5
          done

  selenium_tests:
    needs: angular_server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          google-chrome --version
          chromedriver --version
      - name: Install Python dependencies for Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
      - name: Run Selenium tests
        run: |
          cd selenium
          python test_dashboard_restaurateur.py
